---
collections:
  - name: community.general
    version: "6.4.0"
  - name: community.kubernetes
    version: "1.2.3"
  - name: kubernetes.core
    version: "2.4.0"
  - name: ansible.posix
    version: "1.4.0"
