---
- name: Prepare UE "{{ ue }}" via jump host
  shell: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -n root@{{ ue }} 'prepare-ue --dnn="{{ hostvars[ue].dnn }}"'
  delegate_to: faraday.inria.fr

- name: Start UE "{{ ue }}" via jump host
  shell: ssh root@{{ ue }} 'start.sh -F "{{ hostvars[ue].dnn }}"'
  delegate_to: faraday.inria.fr