---
- name: Clone 5G-Monarch repo
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: main
    update: yes

- name: Label {{ worker_node_name }} for Monarch scheduling
  command: kubectl label node {{ worker_node_name }} {{ monarch_label_key }}={{ monarch_label_val }} --overwrite
  changed_when: "'already has a value' not in label_result.stdout"
  register: label_result

- name: Ensure {{ monarch_ns }} namespace exists
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ monarch_ns }}"

- name: Patch namespace with default nodeSelector
  kubernetes.core.k8s:
    state: patched
    kind: Namespace
    name: "{{ monarch_ns }}"
    merge_type: merge
    definition:
      metadata:
        annotations:
          scheduler.kubernetes.io/node-selector: "{{ monarch_label_key }}={{ monarch_label_val }}"

- name: Get nodes JSON
  command: kubectl get nodes -o json
  register: nodes_json

- name: Extract worker-node IP
  set_fact:
    monarch_node_ip: >-
      {{
        (nodes_json.stdout | from_json)
        | json_query("items[?!(metadata.labels.\"node-role.kubernetes.io/control-plane\")].status.addresses[0].address")
        | first
      }}

- name: Patch NODE_IP in .env
  lineinfile:
    path: "{{ repo_dest }}/.env"
    regexp: '^NODE_IP=.*'
    line: 'NODE_IP="{{ monarch_node_ip }}"'
    create: yes

- name: Install Python requirements
  ansible.builtin.pip:
    requirements: "{{ repo_dest }}/requirements.txt"
    executable: pip3

- name: Deploy Monarch External Components (SO, NFVO)
  ansible.builtin.debug:
    msg: "Starting deployment of Monarch external components..."

- import_tasks: deploy_external.yml

- name: Deploy Monarch Core Components (Data, Monitoring)"
  ansible.builtin.debug:
    msg: "Starting deployment of Monarch core components..."

- import_tasks: deploy_core.yml

- name: Deploy Monarch NSS Components (NSSDC, Prometheus)
  ansible.builtin.debug:
    msg: "Starting deployment of Monarch NSS components..."

- import_tasks: deploy_nss.yml
