- name: Ensure /mnt/{{ storage }} mount point exists
  file:
    path: /mnt/{{ storage }}
    state: directory
    mode: '0755'

- name: Mount /dev/{{ storage }} to /mnt/data
  mount:
    path: /mnt/{{ storage }}
    src: /dev/{{ storage }}
    fstype: ext4
    state: mounted

- name: Create MongoDB data directory with correct ownership
  file:
    path: /mnt/data/mongodb
    state: directory
    owner: 1001
    group: 1001
    mode: '0755'

- name: Create MinIO data directory with correct ownership
  ansible.builtin.file:
    path: /mnt/data/minio
    state: directory
    owner: 1000
    group: 1000
    mode: '0755'

- name: Create Thanos data directory
  file:
    path: /mnt/data/thanos
    state: directory
    mode: '0755'

- name: Create Prometheus data directory
  file:
    path: /mnt/data/prometheus
    state: directory
    owner: 65534
    group: 65534
    mode: '0755'