---
- name: Ensure required apt packages are installed
  apt:
    name:
      - vim
      - tmux
      - git
      - curl
      - iproute2
      - iputils-ping
      - iperf3
      - tcpdump
      - python3-pip
      - jq
    state: present
    update_cache: yes

- name: Install virtualenv using pip3
  pip:
    name: virtualenv

- name: Disable swap
  shell: |
    swapoff -a
    sed -i.bak '/ swap / s/^/#/' /etc/fstab
  become: true

- name: Load kernel modules for Kubernetes networking
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  become: true

- name: Ensure kernel modules are loaded on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  become: true

- name: Set sysctl parameters for Kubernetes networking
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  become: true

- name: Apply sysctl parameters
  command: sysctl --system
  become: true

- name: Ensure CPUAffinity is set in system.conf
  lineinfile:
    path: /etc/systemd/system.conf
    regexp: '^CPUAffinity='
    line: 'CPUAffinity=2-7'
    state: present
  when: inventory_hostname == groups['ran_node'][0] and hostvars[groups['faraday'][0]].rru in ['jaguar', 'panther']

- name: Reload sysctl
  command: sysctl -p
  when: inventory_hostname == groups['ran_node'][0] and hostvars[groups['faraday'][0]].rru in ['jaguar', 'panther']

- name: Reload systemd config
  command: systemctl daemon-reexec
  when: inventory_hostname == groups['ran_node'][0] and hostvars[groups['faraday'][0]].rru in ['jaguar', 'panther']
