---
- name: (POS) Free any existing allocation for {{ node }}
  shell: pos allocations free -k "{{ node }}"

- name: (POS) Allocate {{ node }} 
  shell: pos allocations allocate "{{ node }}"

- name: (POS) Flash image to {{ node }}
  shell: >
    pos nodes image --staging "{{ node }}" "{{ pos_image }}"

- name: (POS) Reset {{ node }}
  shell: pos nodes reset "{{ node }}"

- name: (POS) Wait for SSH to be available on {{ node }}
  wait_for:
    host: "{{ node }}"
    port: 22
    timeout: 300
