---
- name: (POS) Free any existing allocation
  shell: pos allocations free -k "{{ item }}"
  loop: "{{ nodes }}"

- name: (POS) Allocate the node
  shell: pos allocations allocate "{{ item }}"
  loop: "{{ nodes }}"

- name: (POS) Flash image to node
  shell: >
    pos nodes image --staging "{{ item }}" "{{ pos_image }}"
  loop: "{{ nodes }}"

- name: (POS) Reset the node
  shell: pos nodes reset "{{ item }}"
  loop: "{{ nodes }}"

- name: (POS) Wait for SSH to be available
  wait_for:
    host: "{{ item }}"
    port: 22
    timeout: 300
  loop: "{{ nodes }}"
