- name: Create reverse SSH tunnel from {{ inventory_hostname }} to Webshell
  shell: >
    nohup ssh -N -R {{ grafana_port }}:localhost:{{ grafana_port }}
    {{ ansible_user }}@{{ duckburg_host }} > /dev/null 2>&1 &

- name: Show Grafana public link
  debug:
    msg: |
      Monarch dashboard is now accessible at: {{ duckburg_host }}:{{ grafana_port }}. Login: admin / monarch-operator
