---
- name: Ensure autossh is installed locally
  become: false
  delegate_to: localhost
  ansible.builtin.package:
    name: autossh
    state: present

- name: Start local -> webshell -> sopnode port forwarding with autossh
  become: false
  delegate_to: localhost
  ansible.builtin.shell: |
    pkill -f "autossh.*{{ grafana_port }}" || true
    nohup autossh -M 0 -f \
      -i {{ ssh_key }} \
      -o "ExitOnForwardFailure yes" \
      -o "ServerAliveInterval 30" \
      -o "ServerAliveCountMax 3" \
      -L {{ grafana_port }}:localhost:{{ grafana_port }} \
      -J {{ webshell_user }}@{{ webshell_host }}:{{ webshell_port }} \
      root@{{ sopnode_host }} \
      sleep 10
  args:
    executable: /bin/bash
