---
- name: Add ngrok GPG key
  ansible.builtin.apt_key:
    url: https://ngrok-agent.s3.amazonaws.com/ngrok.asc
    state: present

- name: Add ngrok APT repository
  ansible.builtin.apt_repository:
    repo: deb https://ngrok-agent.s3.amazonaws.com buster main
    state: present
    filename: ngrok

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install ngrok
  ansible.builtin.apt:
    name: ngrok
    state: present

- name: Add ngrok authtoken
  command: "ngrok config add-authtoken {{ ngrok_authtoken }}"
  args:
    creates: ~/.config/ngrok/ngrok.yml
  when: ngrok_authtoken | length > 0

- name: Start ngrok tunnel to Grafana port
  command: "nohup ngrok http {{ grafana_port }}"
  async: 1
  poll: 0
  changed_when: false

- name: Wait for ngrok API to respond
  wait_for:
    host: 127.0.0.1
    port: 4040
    delay: 3
    timeout: 30

- name: Get public ngrok URL
  uri:
    url: http://localhost:4040/api/tunnels
    return_content: yes
  register: tunnel_api

- name: Extract public HTTPS URL safely
  set_fact:
    grafana_public_url: >-
      {{
        (tunnel_api.json.tunnels | selectattr('proto', 'equalto', 'https') | list | first).public_url
        if (tunnel_api.json.tunnels | selectattr('proto', 'equalto', 'https') | list)
        else 'NO_HTTPS_TUNNEL_FOUND'
      }}

- name: Show Grafana public link
  debug:
    msg: |
      Monarch dashboard is now accessible at: {{ grafana_public_url }}. Login: admin / monarch-operator
