---
- name: Join the node to the cluster
  command: >
    kubeadm join {{ control_plane_endpoint }}
    --token {{ kubeadm_token }}
    --discovery-token-ca-cert-hash {{ discovery_token_ca_cert_hash }}
  register: join_out
  changed_when: join_out.rc == 0
  failed_when: join_out.rc != 0

- name: Wait 10 seconds for kubelet to stabilize
  pause:
    seconds: 10