---
- name: Add OpenEBS Helm repository
  kubernetes.core.helm_repository:
    name: openebs
    repo_url: https://openebs.github.io/charts
  become: true

- name: Update Helm repositories
  command: helm repo update
  become: true

- name: Install OpenEBS using Helm
  kubernetes.core.helm:
    name: openebs
    chart_ref: openebs/openebs
    namespace: openebs
    create_namespace: true
  become: true

- name: Patch OpenEBS storage class to be default
  shell: >
    kubectl patch storageclass openebs-hostpath -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
  become: true
