---
- name: Power ON "{{ rru }}" PDU outlet
  shell: rhubarbe pdu on "{{ rru }}"
  delegate_to: faraday.inria.fr

- name: Verify PDU status
  shell: rhubarbe pdu status "{{ rru }}"
  register: pdu_status
  delegate_to: faraday.inria.fr

- name: Show PDU status
  debug:
    var: pdu_status.stdout