---
- name: Create kube-flannel namespace 
  kubernetes.core.k8s:
    name: kube-flannel
    api_version: v1
    kind: Namespace
    state: present
  become: true

- name: Apply namespace with pod-security label
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-flannel
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present
    apply: yes
  become: true

- name: Add Flannel Helm repo
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: https://flannel-io.github.io/flannel/
  become: true

- name: Install Flannel via Helm
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    release_namespace: kube-flannel
    create_namespace: false
    state: present
    wait: true
    wait_timeout: 300s
  become: true

- name: Retrieve Multus
  ansible.builtin.git:
    repo: https://github.com/k8snetworkplumbingwg/multus-cni.git
    dest: multus-cni
    version: v4.0.1
    force: yes

- name: Patch Multus DaemonSet manifest resource requests/limits
  ansible.builtin.replace:
    path: multus-cni/deployments/multus-daemonset.yml
    regexp: 'requests:\n\s{6}cpu: "100m"\n\s{6}memory: "50Mi"\n\s{4}limits:\n\s{6}cpu: "100m"\n\s{6}memory: "50Mi"'
    replace: |
      requests:
        cpu: "300m"
        memory: "300Mi"
      limits:
        cpu: "500m"
        memory: "500Mi"

- name: Install Multus DaemonSet with patched resources
  kubernetes.core.k8s:
    state: present
    src: multus-cni/deployments/multus-daemonset.yml

- name: Wait for Multus DaemonSet to be ready
  kubernetes.core.k8s_info:
    kind: DaemonSet
    namespace: kube-system
    name: kube-multus-ds
  register: multus_ds_info
  until: multus_ds_info.resources[0].status.desiredNumberScheduled == multus_ds_info.resources[0].status.numberReady
  retries: 20
  delay: 15
