---
- name: Create kube-flannel namespace 
  kubernetes.core.k8s:
    name: kube-flannel
    api_version: v1
    kind: Namespace
    state: present
  become: true

- name: Apply namespace with pod-security label
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: kube-flannel
        labels:
          pod-security.kubernetes.io/enforce: privileged
    state: present
    apply: yes
  become: true

- name: Add Flannel Helm repo
  kubernetes.core.helm_repository:
    name: flannel
    repo_url: https://flannel-io.github.io/flannel/
  become: true

- name: Install Flannel via Helm
  kubernetes.core.helm:
    name: flannel
    chart_ref: flannel/flannel
    release_namespace: kube-flannel
    create_namespace: false
    state: present
    wait: true
    wait_timeout: 300s
  become: true

- name: Upload Multus DaemonSet manifest with patched resources to the master node
  copy:
    src: multus-daemonset.yml
    dest: /root/multus-daemonset.yml
    mode: '0644'
  become: true

- name: Install Multus DaemonSet
  kubernetes.core.k8s:
    state: present
    src: /root/multus-daemonset.yml
  become: true

- name: Wait for Multus DaemonSet to be ready
  kubernetes.core.k8s_info:
    kind: DaemonSet
    namespace: kube-system
    name: kube-multus-ds
  register: multus_ds_info
  until: multus_ds_info.resources[0].status.desiredNumberScheduled == multus_ds_info.resources[0].status.numberReady
  retries: 20
  delay: 15
  become: true