---
- name: Clone (or update) open5gs-k8s repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: main
    update: yes

- name: Ensure namespace {{ namespace }} exists
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ namespace }}"
    state: present

- name: Deploy common Open5GS NFs
  kubernetes.core.k8s:
    apply: yes
    state: present
    src: "{{ repo_dest }}/open5gs/common/{{ item }}"
    namespace: "{{ namespace }}"
  loop: "{{ common_nfs }}"
  register: nf_apply_results

- name: Deploy slice-specific SMF and UPF
  include_tasks: deploy_slice.yml
  loop: "{{ slice_defs }}"
  loop_control:
    loop_var: item
