---
- name: (POST5G) power-on USRP {{ rru }} from localhost
  ansible.builtin.shell: post5g nodes start {{ rru }}
  delegate_to: localhost
  run_once: true

- name: Update HOST_GNB variable in prepare-demo-oai.sh
  ansible.builtin.lineinfile:
    path: "{{ repo_dest }}/oai-ran/prepare-demo-oai.sh"
    regexp: '^HOST_GNB='
    line: "HOST_GNB=\"{{ ansible_hostname }}\""
    backrefs: true

- name: Update LOCAL_INTERFACE variable in prepare-demo-oai.sh
  ansible.builtin.lineinfile:
    path: "{{ repo_dest }}/oai-ran/prepare-demo-oai.sh"
    regexp: '^LOCAL_INTERFACE='
    line: "LOCAL_INTERFACE=\"{{ nic_interface }}\""
    backrefs: true

- name: Run prepare-demo-oai.sh to pull & configure OAI RAN charts
  ansible.builtin.command: "{{ script_path }} -a -R {{ rru }}"
  args:
    chdir: "{{ repo_dest }}/oai-ran"
  register: ran_script
  changed_when: "'OAI5G charts are now configured' in ran_script.stdout"

- name: Install OAI FlexRIC chart using Helm
  kubernetes.core.helm:
    name: oai-flexric
    chart_ref: "{{ charts_base }}/oai-flexric"
    release_namespace: "{{ ran_namespace }}"
    create_namespace: true
    state: present
    update_repo_cache: true
    wait: true
  register: helm_flex

- name: Install OAI gNB chart using Helm
  kubernetes.core.helm:
    name: oai-gnb
    chart_ref: "{{ charts_base }}/oai-gnb"
    release_namespace: "{{ ran_namespace }}"
    create_namespace: true
    state: present
    update_repo_cache: true
    wait: true
  register: helm_gnb
