---
- name: Iperf3 client test on each UE via Faraday
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Run iperf3 from each UE
      shell: ssh root@{{ ue }} 'iperf3 -c {{ hostvars[ue].upf_ip }} -B {{ hostvars[ue].ip }} -t 100'
      loop: "{{ groups['qhats'] }}"
      loop_control:
        loop_var: ue
      delegate_to: faraday.inria.fr
