---
- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes
  become: true

- name: Make keyring dir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true

- name: Download & de-armor Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg |
    gpg --dearmor -o /etc/apt/keyrings/docker.gpg
  args:
    creates: /etc/apt/keyrings/docker.gpg
  register: docker_key
  changed_when: docker_key.stdout is not defined
  become: true

- name: Ensure key readable
  file:
    path: /etc/apt/keyrings/docker.gpg
    mode: '0644'
  become: true

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"
    filename: docker
    state: present
  become: true

- name: Refresh apt cache
  apt:
    update_cache: yes
  become: true

- name: Install containerd
  apt:
    name: containerd.io
    state: present
    update_cache: yes
  become: true

- name: Create /etc/containerd directory
  file:
    path: /etc/containerd
    state: directory
  become: true

- name: Generate default containerd config
  command: containerd config default
  register: containerd_cfg
  changed_when: false
  become: true

- name: Write config.toml
  copy:
    dest: /etc/containerd/config.toml
    content: "{{ containerd_cfg.stdout }}"
  become: true

- name: Enable systemd-cgroup
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  become: true

- name: Switch snapshotter to native
  replace:
    path: /etc/containerd/config.toml
    regexp: 'snapshotter = "overlayfs"'
    replace: 'snapshotter = "native"'
  become: true

- name: Restart & enable containerd
  systemd:
    name: containerd
    enabled: yes
    state: restarted
  become: true
