---
- name: Power ON RRU2 on R2Lab
  hosts: faraday
  vars:
    rru: "{{ hostvars[groups['faraday'][0]].rru2 }}"
  roles:
    - role: r2lab/rru

- name: Deploy Second gNB
  hosts: ran_node
  vars:
    rru: "{{ hostvars[groups['faraday'][0]].rru2 }}"
    ran_ns: "gnb2_test"
  roles:
    - role: 5g/ran
