---
- hosts: webshell
  gather_facts: false
  tasks:
    - name: Run pos role in parallel for each sopnode
      ansible.builtin.command: >
        ansible-playbook -i inventory/hosts.ini playbooks/run_pos.yml --extra-vars "node={{ item }}" -c local
      args: 
        chdir: "{{ playbook_dir | dirname }}"
      async: 1800
      poll: 0
      loop: "{{ groups['sopnodes'] }}"
      loop_control:
        label: "{{ item }}"
      register: prepare_jobs

    - name: Wait for role completion on all Sopnodes
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 10
      loop: "{{ prepare_jobs.results }}"
      loop_control:
        label: "{{ item.item }}"

- name: Setup Sopnodes
  hosts: sopnodes
  roles:
    - role: setup/common
    - role: setup/containerd
    - role: setup/k8s/k8s_setup
    - role: setup/ovs
    - role: setup/optimization/cpu

- name: Create and Setup Kubernetes Cluster On Master
  hosts: k8s_master
  roles:
    - role: setup/k8s/cluster_create
    - role: setup/cni
    - role: setup/storage

- name: Join Kubernetes Cluster on Workers
  hosts: k8s_workers
  become: true
  roles:
    - role: setup/k8s/cluster_join

- name: Configure GRE Tunnel From Core Node to RAN Node
  hosts: core_node
  vars:
    ip: "{{ hostvars[groups['ran_node'][0]].ip }}"
  roles:
    - role: setup/gre_tunnel

- name: Configure GRE Tunnel From RAN Node to Core Node
  hosts: ran_node
  vars:
    ip: "{{ hostvars[groups['core_node'][0]].ip }}"
  roles:
    - role: setup/gre_tunnel

- name: Deploy Open5gs Core
  hosts: core_node
  roles:
    - role: 5g/core

- name: Cleanup R2Lab
  hosts: faraday
  roles:
    - role: r2lab/cleanup

- hosts: faraday
  tasks:
    - name: Setup UEs on R2Lab
      ansible.builtin.command: >
        ansible-playbook -i inventory/hosts.ini playbooks/run_setup_ue.yml --extra-vars "ue={{ item }} -c local"
      args: 
        chdir: "{{ playbook_dir | dirname }}"
      async: 1800
      poll: 0
      loop: "{{ groups['qhats'] }}"
      loop_control:
        label: "{{ item }}"
      register: prepare_ue_jobs

    - name: Wait for role completion on all UEs
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 10
      loop: "{{ prepare_ue_jobs.results }}"
      loop_control:
        label: "{{ item.item }}"

- name: Power ON RRU on R2Lab
  hosts: faraday
  roles:
    - role: r2lab/rru

- name: Deploy OAI RAN
  hosts: ran_node
  roles:
    - role: setup/optimization/nic
    - role: setup/netplan
    - role: 5g/ran

- hosts: faraday
  tasks:
    - name: Connect UEs on R2Lab to 5g network
      include_role:
        name: r2lab/ue/connect
      vars:
        ue: "{{ item }}"
      loop: "{{ groups['qhats'] }}"
      loop_control:
        label: "{{ item }}"
      ignore_errors: true

- name: Deploy 5G-Monarch for monitoring
  hosts: monitor_node
  roles:
    - role: monarch/deploy
    - role: monarch/monitoring