---
- name: Prepare Sopnodes 
  hosts: localhost
  strategy: free
  tasks:
    - include_role:
        name: pos
      vars:
        node: "{{ item }}"
      loop: "{{ groups['sopnodes'] }}"
      loop_control:
        label: "{{ item }}"

- name: Setup Sopnodes
  hosts: sopnodes
  strategy: free
  roles:
    - role: setup/common
    - role: setup/containerd
    - role: setup/k8s/k8s_setup
    - role: setup/ovs
    - role: setup/optimization/cpu

- name: Create and Setup Kubernetes Cluster On Master
  hosts: k8s_master
  roles:
    - role: setup/k8s/cluster_create
    - role: setup/cni
    - role: setup/storage

- name: Join Kubernetes Cluster on Workers
  hosts: k8s_workers
  strategy: free
  become: true
  roles:
    - role: setup/k8s/cluster_join

- name: Deploy Open5gs Core
  hosts: core_node
  roles:
    - role: 5g/core

- name: Setup UEs on R2Lab
  hosts: faraday
  strategy: free
  tasks:
    - include_role:
        name: r2lab/setup
      vars:
        ue: "{{ item }}"
      loop: "{{ groups['qhats'] }}"
      loop_control:
        label: "{{ item }}"

- name: Deploy OAI RAN
  hosts: ran_node
  roles:
    - role: setup/optimization/nic
    - role: setup/netplan
    - role: 5g/ran

- name: Connect UEs on R2Lab to 5g network
  hosts: faraday
  strategy: free
  tasks:
    - include_role:
        name: r2lab/connect
      vars:
        ue: "{{ item }}"
      loop: "{{ groups['qhats'] }}"
      loop_control:
        label: "{{ item }}"

- name: Deploy 5G-Monarch for monitoring
  hosts: monitor_node
  vars_files:
    - ../vault.yml
  vars:
    worker_node_name: "{{ inventory_hostname }}"
  roles:
    - role: monarch/deploy
    - role: monarch/monitoring
    - role: monarch/expose