---
- name: Prepare Sopnodes 
  hosts: localhost
  vars:
    nodes: "{{ groups['sopnodes'] }}"
  roles:
    - role: pos

- name: Setup Sopnodes
  hosts: sopnodes
  roles:
    - role: setup/common
    - role: setup/containerd
    - role: setup/k8s/k8s_setup
    - role: setup/ovs

- name: Create and Setup Kubernetes Cluster On Master
  hosts: sopnode-f1
  roles:
    - role: setup/k8s/cluster_create
    - role: setup/cni
    - role: setup/storage
    - role: setup/netplan
    - role: setup/optimization

# - name: Join Cluster on Worker
#   hosts: sopnode-f1
#   vars:
#     control_plane_endpoint: "{{ hostvars['sopnode-f3'].ansible_default_ipv4.address }}:6443"
#     kubeadm_token: "{{ hostvars['sopnode-f3'].kubeadm_token }}"
#     discovery_token_ca_cert_hash: "{{ hostvars['sopnode-f3'].ca_hash }}"
#   roles:
#     - role: setup/k8s/cluster_join
#     - role: setup/netplan
#     - role: setup/optimization

- name: Deploy Open5gs Core
  hosts: sopnode-f1
  roles:
    - role: 5g/core

- name: Deploy OAI RAN
  hosts: sopnode-f1
  roles:
    - role: 5g/ran

- name: Setup and connect UEs on R2Lab
  hosts: faraday
  tasks:
    - name: Setup and connect {{ item }} on R2Lab
      include_role:
        name: r2lab
      vars:
        ue: "{{ item }}"
      loop: "{{ groups['qhats'] }}"

- name: Deploy 5G-Monarch for monitoting
  hosts: sopnode-f1
  vars_files:
    - vault.yml
  roles:
    - role: monarch/deploy
    - role: monarch/monitoring
    - role: monarch/expose