---
- name: Prepare Sopnodes 
  hosts: localhost
  tasks:
    - name: Prepare {{ item }}
      include_role:
        name: pos
      vars:
        node: "{{ item }}"
      loop: "{{ groups['sopnodes'] }}"

- name: Setup Sopnodes
  hosts: sopnodes
  roles:
    - role: setup/common
    - role: setup/containerd
    - role: setup/k8s/k8s_setup
    - role: setup/ovs
    - role: setup/optimization

- name: Create and Setup Kubernetes Cluster On Master
  hosts: k8s_master
  roles:
    - role: setup/k8s/cluster_create
    - role: setup/cni
    - role: setup/storage

- name: Join Kubernetes Cluster on Workers
  hosts: k8s_workers
  become: true
  vars:
    master_host: "{{ groups['k8s_master'][0] }}"
    control_plane_endpoint: "{{ hostvars[master_host].ansible_default_ipv4.address }}:6443"
    kubeadm_token: "{{ hostvars[master_host].kubeadm_token }}"
    discovery_token_ca_cert_hash: "{{ hostvars[master_host].ca_hash }}"
  roles:
    - role: setup/k8s/cluster_join

- name: Deploy Open5gs Core
  hosts: core_node
  roles:
    - role: 5g/core

- name: Setup UEs on R2Lab
  hosts: faraday
  tasks:
    - name: Setup {{ item }} on R2Lab
      include_role:
        name: r2lab/setup
      vars:
        ue: "{{ item }}"
      loop: "{{ groups['qhats'] }}"

- name: Deploy OAI RAN
  hosts: core_ran
  roles:
    - role: setup/netplan
    - role: 5g/ran

- name: Connect UEs on R2Lab to 5g network
  hosts: faraday
  tasks:
    - name: Setup {{ item }} on R2Lab
      include_role:
        name: r2lab/connect
      vars:
        ue: "{{ item }}"
      loop: "{{ groups['qhats'] }}"

- name: Deploy 5G-Monarch for monitoring
  hosts: monitor_node
  vars_files:
    - ../vault.yml
  roles:
    - role: monarch/deploy
    - role: monarch/monitoring
    - role: monarch/expose