---
- name: Setup first fit node on R2Lab
  hosts: faraday
  vars:
    fit_node: "{{ groups['fit_nodes'][0] }}"
    fit_number: "{{ hostvars[fit_node].fit_number }}"
    fit_usrp: "{{ hostvars[fit_node].fit_usrp }}"
  roles:
    - role: scenarios/interference/setup

- name: Setup first fit node for spectre visualization (uhd_fft)
  hosts: faraday
  vars:
    fit_node: "{{ groups['fit_nodes'][0] }}"
  roles:
    - role: scenarios/interference/watch

- name: Setup second fit node on R2Lab for noise genaration
  hosts: faraday
  vars:
    fit_node: "{{ groups['fit_nodes'][1] }}"
    fit_number: "{{ hostvars[fit_node].fit_number }}"
    fit_usrp: "{{ hostvars[fit_node].fit_usrp }}"
  roles:
    - role: scenarios/interference/setup
      when: hostvars[groups['faraday'][0]].interference_usrp == 'fit'

- name: Setup interference USRP on R2Lab
  hosts: faraday
  vars:
    rru: "{{ hostvars[groups['faraday'][0]].interference_usrp }}"
  roles:
    - role: r2lab/rru
      when: hostvars[groups['faraday'][0]].interference_usrp in ['n300', 'n320']

- name: Connect first UE on R2Lab to the 5G network
  hosts: faraday
  roles:
    - role: r2lab/ue/connect
      vars:
        ue: "{{ groups['qhats'][0] }}"
