---
- name: Connect first 4 UEs on R2Lab to the 5G network
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Include connect role for each UE
      include_role:
        name: r2lab/ue/connect
      vars:
        ue: "{{ item }}"
      loop: "{{ groups['qhats'][:4] }}"
      loop_control:
        label: "{{ item }}"
