---
- name: Connect first 4 UEs on R2Lab to the 5G network
  hosts: faraday
  roles:
    - role: r2lab/ue/connect
      vars:
        ue: "{{ item }}"
  loop: "{{ groups['qhats'][:4] }}"
  loop_control:
    label: "{{ item }}"

- name: Run sequential iperf3 tests on first 4 UEs
  hosts: faraday
  gather_facts: false
  vars:
    ue_list: "{{ groups['qhats'][:4] }}"
  tasks:
    - name: Run iperf3 test on each UE sequentially
      block:
        - name: Start bidirectional iperf3 on {{ item }} in background for 5 minutes
          shell: >
            ssh root@{{ item }}
            'iperf3 -c {{ hostvars[item].upf_ip }} --bidir -t 300 -J log_iperf_test.json'
          delegate_to: faraday.inria.fr
          async: 1800
          poll: 0
          register: iperf_job

        - name: Wait 60 seconds before next UE
          wait_for:
            timeout: 60
      loop: "{{ ue_list }}"
      loop_control:
        label: "{{ item }}"
