---
- name: Setup noise generator on R2Lab
  hosts: faraday
  roles:
    - role: scenarios/interference/setup

- name: Run interference test on R2Lab
  hosts: faraday
  roles:
    - role: scenarios/interference/run