---
- name: Setup iperf3 on UPFs
  hosts: core_node
  gather_facts: false
  roles:
    - role: scenarios/iperf/upf

- name: Iperf3 reverse client test on each UE via Faraday (Downlink Test)
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Run iperf3 client each UE for 200s
      shell: ssh root@{{ ue }} 'iperf3 -c {{ hostvars[ue].upf_ip }} -B {{ hostvars[ue].ip }} -t 200 -R'
      loop: "{{ groups['qhats'] }}"
      loop_control:
        loop_var: ue
      delegate_to: faraday.inria.fr

- name: Iperf3 client test on each UE via Faraday (Uplink Test)
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Run iperf3 client each UE for 200s
      shell: ssh root@{{ ue }} 'iperf3 -c {{ hostvars[ue].upf_ip }} -B {{ hostvars[ue].ip }} -t 200'
      loop: "{{ groups['qhats'] }}"
      loop_control:
        loop_var: ue
      delegate_to: faraday.inria.fr