---
- name: Run sequential iperf3 tests on first 4 UEs
  hosts: faraday
  gather_facts: false
  vars:
    ue_list: "{{ groups['qhats'][:4] }}"
  tasks:
    - name: Run iperf3 test on each UE sequentially
      block:
        - name: Start bidirectional iperf3 on {{ item }} in background for 400 seconds
          shell: >
            ssh root@{{ item }}
            'iperf3 -c {{ hostvars[item].upf_ip }} --bidir -t 400 -J log_iperf_test.json'
          delegate_to: faraday.inria.fr
          async: 1800
          poll: 0
          register: iperf_job

        - name: Wait 100 seconds before next UE
          wait_for:
            timeout: 100
      loop: "{{ ue_list }}"
      loop_control:
        label: "{{ item }}"

- name: Wait for Iperf job to finish
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Wait for iperf job
      async_status:
        jid: "{{ iperf_job.ansible_job_id }}"
      register: result
      until: result.finished
      retries: 100
      delay: 10

