---
- name: Setup iperf3 on UPFs
  hosts: core_node
  gather_facts: false
  roles:
    - role: scenarios/iperf/upf

- name: Iperf3 reverse client test on each UE via Faraday (Downlink Test)
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Run iperf3 client each UE for 200s
      shell: ssh root@{{ ue }} 'iperf3 -c {{ hostvars[ue].upf_ip }} -B {{ hostvars[ue].ip }} -t 200 -R'
      loop: "{{ groups['qhats'] }}"
      loop_control:
        loop_var: ue
      delegate_to: faraday.inria.fr
      async: 1800
      poll: 0
      register: test_down_jobs
    
    - name: Wait for iperf3 test completion on all UEs
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 10
      loop: "{{ test_down_jobs.results }}"
      loop_control:
        label: "{{ item.item }}"
