---
- name: Setup Iperf on UPFs
  hosts: core_node
  gather_facts: false
  roles:
    - role: scenarios/iperf/upf

- name: Run iperf3 Downlink and Uplink in parallel on all UEs
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Start iperf3 DL test for UE1 in background
      shell: ssh root@qhat01 'iperf3 -c {{ hostvars[qhat01].upf_ip }} -B {{ hostvars[ue].ip }} -t 100 -R -J log_dl.json'
      delegate_to: faraday.inria.fr
      async: 1800
      poll: 0
      register: down_job_1

    - name: Start iperf3 UL test for UE2 in background
      shell: ssh root@qhat02 'iperf3 -c {{ hostvars[qhat02].upf_ip }} -B {{ hostvars[ue].ip }} -t 100 -J log_ul.json'
      delegate_to: faraday.inria.fr
      async: 1800
      poll: 0
      register: down_job_2

    - name: Start iperf3 DL test for UE3 in background
      shell: ssh root@qaht03 'iperf3 -c {{ hostvars[qhat03].upf_ip }} -B {{ hostvars[ue].ip }} -t 100 -R -J log_dl.json'
      delegate_to: faraday.inria.fr
      async: 1800
      poll: 0
      register: up_job_1

- name: Bandwidth intervention sequence
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Wait 30 seconds before applying bandwidth limit to qhat01
      wait_for:
        timeout: 30

    - name: Limit bandwidth on qhat01 to 5Mbps
      shell: |
        ssh root@qhat01 'tc qdisc add dev wwan0 root tbf rate 5mbit burst 32kbit latency 400ms'
      delegate_to: faraday.inria.fr

    - name: Wait 30 more seconds before stopping qhat03
      wait_for:
        timeout: 30

    - name: Stop qhat03 UE (simulate disconnect)
      include_role:
        name: r2lab/ue/stop
      vars:
        ue: qhat03

- name: Wait for iperf3 Downlink tests to finish
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Remove limit on qhat01
      shell: |
        ssh root@qhat01 'tc qdisc del dev wwan0 root'
      delegate_to: faraday.inria.fr

    - name: Wait for DL jobs
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: result
      until: result.finished
      retries: 100
      delay: 10
      loop: "{{ down_job_1.results }}"
      loop_control:
        label: "{{ item.item }}"

    - name: Wait for DL jobs
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: result
      until: result.finished
      retries: 100
      delay: 10
      loop: "{{ down_job_2.results }}"
      loop_control:
        label: "{{ item.item }}"

- name: Wait for iperf3 Uplink tests to finish
  hosts: faraday
  gather_facts: false
  tasks:
    - name: Wait for UL jobs
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: result
      until: result.finished
      retries: 100
      delay: 10
      loop: "{{ up_job_1.results }}"
      loop_control:
        label: "{{ item.item }}"
