---
- name: Power ON "{{ ue }}" PDU outlet
  shell: rhubarbe pdu on "{{ ue }}"
  delegate_to: faraday.inria.fr

- name: Verify PDU status
  shell: rhubarbe pdu status "{{ ue }}"
  register: pdu_status
  delegate_to: faraday.inria.fr

- name: Show PDU status
  debug:
    var: pdu_status.stdout

- name: Wait for "{{ ue }}" SSH
  wait_for:
    host: "{{ ue }}"
    port: 22
    timeout: 180
    sleep: 5

- name: Set {{ hostvars[ue].mode }} mode on UE "{{ ue }}" via jump host
  shell: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -n root@{{ ue }} 'set-{{ hostvars[ue].mode }}'
  delegate_to: faraday.inria.fr

- name: Check mode on UE "{{ ue }}" via jump host
  shell: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -n root@{{ ue }} 'check-ue'
  register: mode_status
  delegate_to: faraday.inria.fr

- name: Show used mode on UE "{{ ue }}"
  debug:
    var: mode_status.stdout