---
- name: Power ON "{{ ue }}" PDU outlet
  shell: rhubarbe pdu on "{{ ue }}"
  delegate_to: faraday.inria.fr

- name: Verify PDU status
  shell: rhubarbe pdu status "{{ ue }}"
  register: pdu_status
  delegate_to: faraday.inria.fr

- name: Wait for "{{ ue }}" SSH
  wait_for:
    host: "{{ ue }}"
    port: 22
    timeout: 180
    sleep: 5
  delegate_to: faraday.inria.fr

- name: Set {{ hostvars[ue].mode }} mode on UE "{{ ue }}" via jump host
  shell: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ConnectTimeout=5 -n root@{{ ue }} 'set-{{ hostvars[ue].mode }}'
  delegate_to: faraday.inria.fr
  